# Generated by Django for RAG Enhancement - Phase 4 Multi-Scale Chunking

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0101_add_context_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="chunk_scale",
            field=models.CharField(
                max_length=20,
                default="medium",
                choices=[
                    ("small", "Small (512 tokens)"),
                    ("medium", "Medium (1024 tokens)"),
                    ("large", "Large (2048 tokens)"),
                ],
                help_text="Size scale of this chunk for multi-scale retrieval",
            ),
        ),
    ]
