"""
Tests for Django migration reversibility.

These tests verify that migrations 0100, 0101, and 0102 can be reversed properly.
Django generates reverse operations automatically for AddField, but we verify
the migrations declare the reversible() method correctly.
"""

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Add the src directory to the path for importing the migration
khoj_repo_path = Path(__file__).parent.parent / "khoj-repo" / "src"
sys.path.insert(0, str(khoj_repo_path))


class TestMigration0100Reversible:
    """Test suite for migration 0100_add_search_vector reversibility"""

    @pytest.fixture
    def migration_path(self):
        """Return the path to the migration file."""
        return (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
            / "0100_add_search_vector.py"
        )

    def test_migration_reversible_method_exists(self, migration_path):
        """Test that the migration declares a reversible() method."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify reversible method exists
        assert "def reversible(self):" in content, "Migration should declare reversible() method"
        assert "return True" in content, "reversible() should return True"

    def test_migration_has_addfield_operation(self, migration_path):
        """Test that migration uses AddField which Django can auto-reverse."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify AddField operation exists
        assert "migrations.AddField(" in content, "Migration should use AddField operation"
        assert 'model_name="entry"' in content
        assert 'name="search_vector"' in content

    def test_migration_has_addindex_operation(self, migration_path):
        """Test that migration uses AddIndex which Django can auto-reverse."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify AddIndex operation exists
        assert "migrations.AddIndex(" in content, "Migration should use AddIndex operation"
        assert "entry_search_vector_gin_idx" in content

    def test_reverse_operations_would_be_generated(self, migration_path):
        """Test that reverse operations would be generated for all forward operations."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Count forward operations that Django can auto-reverse
        add_field_count = content.count("migrations.AddField(")
        add_index_count = content.count("migrations.AddIndex(")

        # Each AddField -> RemoveField (auto-generated by Django)
        # Each AddIndex -> RemoveIndex (auto-generated by Django)
        assert add_field_count >= 1, "Should have at least one AddField"
        assert add_index_count >= 1, "Should have at least one AddIndex"

    def test_migration_file_valid_python(self, migration_path):
        """Test that the migration file is valid Python syntax."""
        with open(migration_path, "r") as f:
            content = f.read()

        try:
            compile(content, str(migration_path), "exec")
        except SyntaxError as e:
            pytest.fail(f"Migration file has syntax error: {e}")


class TestMigration0101Reversible:
    """Test suite for migration 0101_add_context_summary reversibility"""

    @pytest.fixture
    def migration_path(self):
        """Return the path to the migration file."""
        return (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
            / "0101_add_context_summary.py"
        )

    def test_migration_reversible_method_exists(self, migration_path):
        """Test that the migration declares a reversible() method."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify reversible method exists
        assert "def reversible(self):" in content, "Migration should declare reversible() method"
        assert "return True" in content, "reversible() should return True"

    def test_migration_has_addfield_operation(self, migration_path):
        """Test that migration uses AddField which Django can auto-reverse."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify AddField operation exists
        assert "migrations.AddField(" in content, "Migration should use AddField operation"
        assert 'model_name="entry"' in content
        assert 'name="context_summary"' in content

    def test_reverse_operations_would_be_generated(self, migration_path):
        """Test that reverse operations would be generated for all forward operations."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Count forward operations that Django can auto-reverse
        add_field_count = content.count("migrations.AddField(")

        # Each AddField -> RemoveField (auto-generated by Django)
        assert add_field_count >= 1, "Should have at least one AddField"

    def test_migration_file_valid_python(self, migration_path):
        """Test that the migration file is valid Python syntax."""
        with open(migration_path, "r") as f:
            content = f.read()

        try:
            compile(content, str(migration_path), "exec")
        except SyntaxError as e:
            pytest.fail(f"Migration file has syntax error: {e}")


class TestMigration0102Reversible:
    """Test suite for migration 0102_add_chunk_scale reversibility"""

    @pytest.fixture
    def migration_path(self):
        """Return the path to the migration file."""
        return (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
            / "0102_add_chunk_scale.py"
        )

    def test_migration_reversible_method_exists(self, migration_path):
        """Test that the migration declares a reversible() method."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify reversible method exists
        assert "def reversible(self):" in content, "Migration should declare reversible() method"
        assert "return True" in content, "reversible() should return True"

    def test_migration_has_addfield_operation(self, migration_path):
        """Test that migration uses AddField which Django can auto-reverse."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Verify AddField operation exists
        assert "migrations.AddField(" in content, "Migration should use AddField operation"
        assert 'model_name="entry"' in content
        assert 'name="chunk_scale"' in content

    def test_reverse_operations_would_be_generated(self, migration_path):
        """Test that reverse operations would be generated for all forward operations."""
        with open(migration_path, "r") as f:
            content = f.read()

        # Count forward operations that Django can auto-reverse
        add_field_count = content.count("migrations.AddField(")

        # Each AddField -> RemoveField (auto-generated by Django)
        assert add_field_count >= 1, "Should have at least one AddField"

    def test_migration_file_valid_python(self, migration_path):
        """Test that the migration file is valid Python syntax."""
        with open(migration_path, "r") as f:
            content = f.read()

        try:
            compile(content, str(migration_path), "exec")
        except SyntaxError as e:
            pytest.fail(f"Migration file has syntax error: {e}")


class TestReverseOperationsExist:
    """Test suite to verify RemoveField operations would be generated for reversals"""

    def test_all_migrations_use_auto_reversible_operations(self):
        """Test that all migrations use operations Django can auto-reverse."""
        migrations_dir = (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
        )

        target_migrations = [
            "0100_add_search_vector.py",
            "0101_add_context_summary.py",
            "0102_add_chunk_scale.py",
        ]

        for migration_name in target_migrations:
            migration_path = migrations_dir / migration_name

            with open(migration_path, "r") as f:
                content = f.read()

            # Verify only auto-reversible operations are used
            # AddField and AddIndex are auto-reversible by Django
            assert "migrations.AddField(" in content, f"{migration_name} should use AddField"

            # Verify no irreversible operations (like RunPython without reverse_code)
            if "migrations.RunPython(" in content:
                # If RunPython is used, it must have reverse_code
                assert "reverse_code=" in content, \
                    f"{migration_name} uses RunPython without reverse_code"

    def test_migration_dependencies_allow_sequential_reversal(self):
        """Test that migrations can be reversed in sequence."""
        migrations_dir = (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
        )

        # Check dependency chain allows sequential reversal
        # 0102 depends on 0101, 0101 depends on 0100
        # So to reverse all: migrate to 0099 (reverses 0100, 0101, 0102)

        m0100_path = migrations_dir / "0100_add_search_vector.py"
        m0101_path = migrations_dir / "0101_add_context_summary.py"
        m0102_path = migrations_dir / "0102_add_chunk_scale.py"

        with open(m0100_path, "r") as f:
            m0100_content = f.read()
        with open(m0101_path, "r") as f:
            m0101_content = f.read()
        with open(m0102_path, "r") as f:
            m0102_content = f.read()

        # Verify dependency chain
        assert '("database", "0099_usermemory")' in m0100_content
        assert '("database", "0100_add_search_vector")' in m0101_content
        assert '("database", "0101_add_context_summary")' in m0102_content

    def test_reversible_method_returns_true(self):
        """Test that all migrations have reversible() returning True."""
        migrations_dir = (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
        )

        target_migrations = [
            "0100_add_search_vector.py",
            "0101_add_context_summary.py",
            "0102_add_chunk_scale.py",
        ]

        for migration_name in target_migrations:
            migration_path = migrations_dir / migration_name

            with open(migration_path, "r") as f:
                content = f.read()

            # Verify reversible method exists and returns True
            assert "def reversible(self):" in content, \
                f"{migration_name} should declare reversible() method"

            # Check that reversible returns True (not False or missing return)
            reversible_start = content.find("def reversible(self):")
            reversible_end = content.find("\n\n", reversible_start)
            reversible_section = content[reversible_start:reversible_end]

            assert "return True" in reversible_section, \
                f"{migration_name} reversible() should return True"


class TestMigrationReversibilityDocumentation:
    """Test suite to verify migration files document reversibility"""

    def test_all_migrations_document_reversibility(self):
        """Test that all migrations have REVERSIBILITY documentation in comments."""
        migrations_dir = (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
        )

        target_migrations = [
            "0100_add_search_vector.py",
            "0101_add_context_summary.py",
            "0102_add_chunk_scale.py",
        ]

        for migration_name in target_migrations:
            migration_path = migrations_dir / migration_name

            with open(migration_path, "r") as f:
                content = f.read()

            # Verify REVERSIBILITY documentation exists
            assert "REVERSIBILITY:" in content, \
                f"{migration_name} should document reversibility"

            # Verify reverse command is documented
            assert "Reverse command:" in content or "reverse command:" in content.lower(), \
                f"{migration_name} should document reverse command"

    def test_migrations_document_reverse_effects(self):
        """Test that migrations document what happens on reverse."""
        migrations_dir = (
            Path(__file__).parent.parent
            / "khoj-repo"
            / "src"
            / "khoj"
            / "database"
            / "migrations"
        )

        target_migrations = [
            "0100_add_search_vector.py",
            "0101_add_context_summary.py",
            "0102_add_chunk_scale.py",
        ]

        for migration_name in target_migrations:
            migration_path = migrations_dir / migration_name

            with open(migration_path, "r") as f:
                content = f.read()

            # Verify reverse effects are documented (RemoveField, RemoveIndex, etc.)
            assert "RemoveField" in content or "RemoveIndex" in content, \
                f"{migration_name} should document reverse effects (RemoveField/RemoveIndex)"
