# Generated by Django for RAG Enhancement - Phase 2 Hybrid Search

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0099_usermemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="search_vector",
            field=SearchVectorField(null=True, blank=True),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=GinIndex(fields=["search_vector"], name="entry_search_vector_gin"),
        ),
    ]
