# Generated by Django for RAG Enhancement - Phase 3 Contextual Chunking

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0100_add_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="context_summary",
            field=models.TextField(
                null=True,
                blank=True,
                default=None,
                help_text="AI-generated context summary for improved retrieval",
            ),
        ),
    ]
