// src/interface/web/app/components/ldapConfig/ldapConfig.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

"use client";

import { useState, useEffect } from "react";
import useSWR from "swr";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useToast } from "@/components/ui/use-toast";

import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import {
    Form,
    FormControl,
    FormDescription,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { 
    Shield, 
    Server, 
    Eye, 
    EyeSlash, 
    TestTube, 
    Save, 
    X,
    CheckCircle,
    AlertCircle,
    Loader2,
    ExternalLink,
    Lock,
    Users,
    FileSearch,
    ShieldCheck,
    ShieldAlert
} from "@phosphor-icons/react";

// =============================================================================
// TYPES & INTERFACES
// =============================================================================

export interface LdapConfig {
    server_url: string;
    bind_dn: string;
    bind_password: string;
    user_search_base: string;
    user_search_filter: string;
    use_tls: boolean;
    verify_tls_certificate: boolean;
    enabled: boolean;
}

export interface LdapConfigFormData {
    serverUrl: string;
    bindDn: string;
    bindPassword: string;
    userSearchBase: string;
    userSearchFilter: string;
    useTls: boolean;
    verifyTlsCertificate: boolean;
    enabled: boolean;
}

export interface LdapConfigProps {
    isAdmin: boolean;
    onSave?: (config: LdapConfig) => Promise<void>;
}

export type ConnectionTestStatus = "idle" | "testing" | "success" | "error";

export interface TestConnectionResult {
    success: boolean;
    message: string;
    details?: {
        users_found?: number;
        bind_success?: boolean;
        search_success?: boolean;
    };
}

// =============================================================================
// FORM VALIDATION SCHEMA (ZOD)
// =============================================================================

export const ldapConfigSchema = z.object({
    serverUrl: z.string()
        .min(1, "Server URL is required")
        .regex(/^ldaps?:\/\/.+/, "Server URL must start with ldap:// or ldaps://")
        .refine((val) => {
            // Basic URL validation for LDAP
            try {
                const url = new URL(val);
                return url.port !== "" || val.includes("://");
            } catch {
                return val.includes("://");
            }
        }, "Please enter a valid LDAP server URL"),
    
    bindDn: z.string()
        .min(1, "Bind DN is required")
        .regex(/^CN=|DC=|OU=/i, "Bind DN should follow LDAP format (e.g., CN=user,DC=domain,DC=com)"),
    
    bindPassword: z.string()
        .min(1, "Bind password is required")
        .min(8, "Password must be at least 8 characters long"),
    
    userSearchBase: z.string()
        .min(1, "User search base is required")
        .regex(/^OU=|DC=/i, "Search base should follow LDAP format (e.g., OU=Users,DC=domain,DC=com)"),
    
    userSearchFilter: z.string()
        .min(1, "User search filter is required")
        .refine((val) => val.includes("{username}"), {
            message: "Filter must contain {username} placeholder",
        }),
    
    useTls: z.boolean().default(true),
    
    verifyTlsCertificate: z.boolean().default(true),
    
    enabled: z.boolean().default(false),
}).refine((data) => {
    // If TLS is not used, certificate verification should be disabled
    if (!data.useTls && data.verifyTlsCertificate) {
        return false;
    }
    return true;
}, {
    message: "TLS certificate verification cannot be enabled when TLS is disabled",
    path: ["verifyTlsCertificate"],
});

export type LdapConfigFormValues = z.infer<typeof ldapConfigSchema>;

// =============================================================================
// API FETCHERS & HOOKS (SWR)
// =============================================================================

const fetcher = (url: string) =>
    fetch(url)
        .then((res) => {
            if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`);
            return res.json();
        })
        .catch((err) => {
            console.error("API fetch error:", err);
            throw err;
        });

/**
 * Hook to fetch and manage LDAP configuration using SWR
 * TODO: Coder - implement actual API endpoint
 */
export function useLdapConfig() {
    const { data, error, isLoading, mutate } = useSWR<LdapConfig>(
        "/api/config/ldap",
        fetcher,
        {
            revalidateOnFocus: false,
            shouldRetryOnError: false,
        }
    );

    return {
        config: data,
        error,
        isLoading,
        mutate,
    };
}

/**
 * Hook to test LDAP connection
 * TODO: Coder - implement actual API endpoint
 */
export async function testLdapConnection(config: LdapConfigFormData): Promise<TestConnectionResult> {
    const response = await fetch("/api/config/ldap/test", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            server_url: config.serverUrl,
            bind_dn: config.bindDn,
            bind_password: config.bindPassword,
            user_search_base: config.userSearchBase,
            user_search_filter: config.userSearchFilter,
            use_tls: config.useTls,
            verify_tls_certificate: config.verifyTlsCertificate,
        }),
    });

    if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message || "Connection test failed");
    }

    return response.json();
}

/**
 * Hook to save LDAP configuration
 * TODO: Coder - implement actual API endpoint
 */
export async function saveLdapConfig(config: LdapConfigFormData): Promise<void> {
    const response = await fetch("/api/config/ldap", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            server_url: config.serverUrl,
            bind_dn: config.bindDn,
            bind_password: config.bindPassword,
            user_search_base: config.userSearchBase,
            user_search_filter: config.userSearchFilter,
            use_tls: config.useTls,
            verify_tls_certificate: config.verifyTlsCertificate,
            enabled: config.enabled,
        }),
    });

    if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message || "Failed to save LDAP configuration");
    }
}

// =============================================================================
// HELPER COMPONENTS
// =============================================================================

/**
 * Password input with show/hide toggle
 * Accessible password field with visibility control
 */
function PasswordInput({
    value,
    onChange,
    placeholder,
    disabled,
    id,
    "aria-describedby": ariaDescribedBy,
    "aria-invalid": ariaInvalid,
}: {
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
    disabled?: boolean;
    id?: string;
    "aria-describedby"?: string;
    "aria-invalid"?: boolean;
}) {
    const [showPassword, setShowPassword] = useState(false);

    return (
        <div className="relative">
            <Input
                id={id}
                type={showPassword ? "text" : "password"}
                value={value}
                onChange={(e) => onChange(e.target.value)}
                placeholder={placeholder}
                disabled={disabled}
                className="pr-10"
                aria-describedby={ariaDescribedBy}
                aria-invalid={ariaInvalid}
                aria-label="Bind password"
            />
            <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 rounded-sm"
                aria-label={showPassword ? "Hide password" : "Show password"}
                aria-pressed={showPassword}
                tabIndex={0}
            >
                {showPassword ? (
                    <EyeSlash className="h-4 w-4" aria-hidden="true" />
                ) : (
                    <Eye className="h-4 w-4" aria-hidden="true" />
                )}
            </button>
        </div>
    );
}

/**
 * Connection test result display component
 */
function ConnectionTestAlert({
    status,
    result,
}: {
    status: ConnectionTestStatus;
    result: TestConnectionResult | null;
}) {
    if (status === "idle") return null;

    if (status === "testing") {
        return (
            <Alert className="mt-4" role="status" aria-live="polite">
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                <AlertTitle>Testing Connection</AlertTitle>
                <AlertDescription>
                    Attempting to connect to the LDAP server...
                </AlertDescription>
            </Alert>
        );
    }

    if (status === "success" && result) {
        return (
            <Alert 
                variant="default" 
                className="mt-4 border-green-500 bg-green-50 dark:bg-green-950"
                role="status"
                aria-live="polite"
            >
                <CheckCircle className="h-4 w-4 text-green-600" aria-hidden="true" />
                <AlertTitle className="text-green-800 dark:text-green-200">Connection Successful</AlertTitle>
                <AlertDescription className="text-green-700 dark:text-green-300">
                    {result.message}
                    {result.details && (
                        <ul className="mt-2 text-sm list-disc list-inside">
                            {result.details.bind_success && (
                                <li>Bind authentication successful</li>
                            )}
                            {result.details.search_success && (
                                <li>User search successful</li>
                            )}
                            {result.details.users_found !== undefined && (
                                <li>Found {result.details.users_found} user(s)</li>
                            )}
                        </ul>
                    )}
                </AlertDescription>
            </Alert>
        );
    }

    if (status === "error" && result) {
        return (
            <Alert 
                variant="destructive" 
                className="mt-4"
                role="alert"
                aria-live="assertive"
            >
                <AlertCircle className="h-4 w-4" aria-hidden="true" />
                <AlertTitle>Connection Failed</AlertTitle>
                <AlertDescription>{result.message}</AlertDescription>
            </Alert>
        );
    }

    return null;
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export function LdapConfigSection({ isAdmin, onSave }: LdapConfigProps) {
    const { toast } = useToast();
    const { config, error: fetchError, isLoading, mutate } = useLdapConfig();
    
    // Local state
    const [connectionTestStatus, setConnectionTestStatus] = useState<ConnectionTestStatus>("idle");
    const [connectionTestResult, setConnectionTestResult] = useState<TestConnectionResult | null>(null);
    const [hasTestedConnection, setHasTestedConnection] = useState(false);
    const [isSaving, setIsSaving] = useState(false);

    // Form setup with react-hook-form and zod validation
    const form = useForm<LdapConfigFormValues>({
        resolver: zodResolver(ldapConfigSchema),
        defaultValues: {
            serverUrl: "",
            bindDn: "",
            bindPassword: "",
            userSearchBase: "",
            userSearchFilter: "(sAMAccountName={username})",
            useTls: true,
            verifyTlsCertificate: true,
            enabled: false,
        },
        mode: "onBlur",
    });

    // Watch form values for conditional logic
    const useTls = form.watch("useTls");

    // Populate form with existing config
    useEffect(() => {
        if (config) {
            form.reset({
                serverUrl: config.server_url || "",
                bindDn: config.bind_dn || "",
                bindPassword: config.bind_password || "",
                userSearchBase: config.user_search_base || "",
                userSearchFilter: config.user_search_filter || "(sAMAccountName={username})",
                useTls: config.use_tls ?? true,
                verifyTlsCertificate: config.verify_tls_certificate ?? true,
                enabled: config.enabled ?? false,
            });
        }
    }, [config, form]);

    /**
     * Handle connection test
     * TODO: Coder - add retry logic and better error handling
     */
    const handleTestConnection = async () => {
        // Validate form before testing
        const isValid = await form.trigger();
        if (!isValid) {
            toast({
                title: "Validation Error",
                description: "Please fix the form errors before testing the connection.",
                variant: "destructive",
            });
            return;
        }

        setConnectionTestStatus("testing");
        setConnectionTestResult(null);

        try {
            const values = form.getValues();
            const result = await testLdapConnection(values);
            
            setConnectionTestStatus("success");
            setConnectionTestResult(result);
            setHasTestedConnection(true);

            toast({
                title: "Connection Test Successful",
                description: result.message,
            });
        } catch (error) {
            const errorMessage = error instanceof Error ? error.message : "Unknown error occurred";
            
            setConnectionTestStatus("error");
            setConnectionTestResult({
                success: false,
                message: errorMessage,
            });

            toast({
                title: "Connection Test Failed",
                description: errorMessage,
                variant: "destructive",
            });
        }
    };

    /**
     * Handle form submission (save)
     * TODO: Coder - add optimistic updates and rollback on error
     */
    const handleSave = async (values: LdapConfigFormValues) => {
        setIsSaving(true);

        try {
            await saveLdapConfig(values);
            
            // Update SWR cache
            mutate({
                server_url: values.serverUrl,
                bind_dn: values.bindDn,
                bind_password: values.bindPassword,
                user_search_base: values.userSearchBase,
                user_search_filter: values.userSearchFilter,
                use_tls: values.useTls,
                verify_tls_certificate: values.verifyTlsCertificate,
                enabled: values.enabled,
            });

            if (onSave) {
                await onSave({
                    server_url: values.serverUrl,
                    bind_dn: values.bindDn,
                    bind_password: values.bindPassword,
                    user_search_base: values.userSearchBase,
                    user_search_filter: values.userSearchFilter,
                    use_tls: values.useTls,
                    verify_tls_certificate: values.verifyTlsCertificate,
                    enabled: values.enabled,
                });
            }

            toast({
                title: "Configuration Saved",
                description: "LDAP configuration has been saved successfully.",
            });

            // Reset test status since config changed
            setHasTestedConnection(false);
            setConnectionTestStatus("idle");
        } catch (error) {
            const errorMessage = error instanceof Error ? error.message : "Failed to save configuration";
            
            toast({
                title: "Save Failed",
                description: errorMessage,
                variant: "destructive",
            });
        } finally {
            setIsSaving(false);
        }
    };

    /**
     * Handle cancel - reset form to last saved values
     */
    const handleCancel = () => {
        if (config) {
            form.reset({
                serverUrl: config.server_url || "",
                bindDn: config.bind_dn || "",
                bindPassword: config.bind_password || "",
                userSearchBase: config.user_search_base || "",
                userSearchFilter: config.user_search_filter || "(sAMAccountName={username})",
                useTls: config.use_tls ?? true,
                verifyTlsCertificate: config.verify_tls_certificate ?? true,
                enabled: config.enabled ?? false,
            });
        }
        setConnectionTestStatus("idle");
        setHasTestedConnection(false);
        
        toast({
            title: "Changes Discarded",
            description: "Form has been reset to the last saved configuration.",
        });
    };

    // If not admin, show access denied message
    if (!isAdmin) {
        return (
            <Card className="w-full lg:w-5/12 border border-gray-300 shadow-md rounded-lg dark:bg-muted dark:border-none border-opacity-50">
                <CardHeader>
                    <div className="flex items-center gap-2">
                        <ShieldAlert className="h-6 w-6 text-muted-foreground" aria-hidden="true" />
                        <CardTitle>LDAP Authentication</CardTitle>
                    </div>
                    <CardDescription>
                        Configure LDAP integration for user authentication
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <div 
                        className="flex items-center justify-center p-8 text-center text-muted-foreground"
                        role="alert"
                        aria-live="polite"
                    >
                        <Lock className="h-12 w-12 mb-4 opacity-50" aria-hidden="true" />
                        <p>You do not have permission to view this section.</p>
                        <p className="text-sm mt-2">Please contact an administrator for access.</p>
                    </div>
                </CardContent>
            </Card>
        );
    }

    if (isLoading) {
        return (
            <Card className="w-full lg:w-5/12 border border-gray-300 shadow-md rounded-lg dark:bg-muted dark:border-none border-opacity-50">
                <CardHeader>
                    <div className="flex items-center gap-2">
                        <Server className="h-6 w-6" aria-hidden="true" />
                        <CardTitle>LDAP Authentication</CardTitle>
                        <Badge variant="secondary" className="ml-2">Admin Only</Badge>
                    </div>
                </CardHeader>
                <CardContent className="flex items-center justify-center p-8">
                    <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" aria-label="Loading LDAP configuration" />
                </CardContent>
            </Card>
        );
    }

    if (fetchError) {
        return (
            <Alert variant="destructive" role="alert" aria-live="assertive">
                <AlertCircle className="h-4 w-4" aria-hidden="true" />
                <AlertTitle>Error Loading Configuration</AlertTitle>
                <AlertDescription>
                    Failed to load LDAP configuration. Please refresh the page or try again later.
                </AlertDescription>
            </Alert>
        );
    }

    return (
        <Card 
            className="w-full lg:w-5/12 border border-gray-300 shadow-md rounded-lg dark:bg-muted dark:border-none border-opacity-50"
            aria-labelledby="ldap-config-title"
        >
            <CardHeader>
                <div className="flex items-center gap-2 flex-wrap">
                    <Server className="h-6 w-6" aria-hidden="true" />
                    <CardTitle id="ldap-config-title">LDAP Authentication</CardTitle>
                    <Badge 
                        variant="secondary" 
                        className="ml-2 bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200"
                    >
                        <Shield className="h-3 w-3 mr-1" aria-hidden="true" />
                        Admin Only
                    </Badge>
                </div>
                <CardDescription>
                    Configure LDAP integration for centralized user authentication. 
                    This allows users to sign in using their existing corporate credentials.
                </CardDescription>
            </CardHeader>

            <Form {...form}>
                <form onSubmit={form.handleSubmit(handleSave)} aria-label="LDAP Configuration Form">
                    <CardContent className="space-y-6">
                        
                        {/* Enable LDAP Toggle */}
                        <FormField
                            control={form.control}
                            name="enabled"
                            render={({ field }) => (
                                <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4">
                                    <div className="space-y-0.5">
                                        <FormLabel className="text-base flex items-center gap-2">
                                            <ShieldCheck className="h-4 w-4" aria-hidden="true" />
                                            Enable LDAP Authentication
                                        </FormLabel>
                                        <FormDescription>
                                            Allow users to authenticate via LDAP
                                        </FormDescription>
                                    </div>
                                    <FormControl>
                                        <Switch
                                            checked={field.value}
                                            onCheckedChange={field.onChange}
                                            aria-label="Toggle LDAP authentication"
                                        />
                                    </FormControl>
                                </FormItem>
                            )}
                        />

                        <Separator className="my-4" />

                        {/* Server Configuration Section */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-2">
                                <Server className="h-4 w-4" aria-hidden="true" />
                                Server Configuration
                            </h3>

                            {/* Server URL */}
                            <FormField
                                control={form.control}
                                name="serverUrl"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel htmlFor="server-url">Server URL</FormLabel>
                                        <FormControl>
                                            <Input
                                                id="server-url"
                                                placeholder="ldaps://ad.company.com:636"
                                                {...field}
                                                aria-describedby="server-url-help"
                                            />
                                        </FormControl>
                                        <FormDescription id="server-url-help">
                                            The LDAP server URL. Use ldaps:// for secure connections (recommended).
                                        </FormDescription>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            {/* Use TLS Toggle */}
                            <FormField
                                control={form.control}
                                name="useTls"
                                render={({ field }) => (
                                    <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4">
                                        <div className="space-y-0.5">
                                            <FormLabel className="text-base">Use TLS</FormLabel>
                                            <FormDescription>
                                                Enable TLS encryption for LDAP connections
                                            </FormDescription>
                                        </div>
                                        <FormControl>
                                            <Switch
                                                checked={field.value}
                                                onCheckedChange={field.onChange}
                                                aria-label="Toggle TLS encryption"
                                            />
                                        </FormControl>
                                    </FormItem>
                                )}
                            />

                            {/* Verify TLS Certificate Toggle - only when TLS is enabled */}
                            {useTls && (
                                <FormField
                                    control={form.control}
                                    name="verifyTlsCertificate"
                                    render={({ field }) => (
                                        <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4 ml-4 border-l-4 border-l-primary">
                                            <div className="space-y-0.5">
                                                <FormLabel className="text-base">Verify TLS Certificate</FormLabel>
                                                <FormDescription>
                                                    Verify the server&apos;s TLS certificate (recommended for production)
                                                </FormDescription>
                                            </div>
                                            <FormControl>
                                                <Switch
                                                    checked={field.value}
                                                    onCheckedChange={field.onChange}
                                                    aria-label="Toggle TLS certificate verification"
                                                />
                                            </FormControl>
                                        </FormItem>
                                    )}
                                />
                            )}
                        </div>

                        <Separator className="my-4" />

                        {/* Authentication Section */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-2">
                                <Lock className="h-4 w-4" aria-hidden="true" />
                                Bind Credentials
                            </h3>

                            {/* Bind DN */}
                            <FormField
                                control={form.control}
                                name="bindDn"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel htmlFor="bind-dn">Bind DN</FormLabel>
                                        <FormControl>
                                            <Input
                                                id="bind-dn"
                                                placeholder="CN=service,OU=Accounts,DC=company,DC=com"
                                                {...field}
                                                aria-describedby="bind-dn-help"
                                            />
                                        </FormControl>
                                        <FormDescription id="bind-dn-help">
                                            The Distinguished Name of the service account used to bind to LDAP.
                                        </FormDescription>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            {/* Bind Password */}
                            <FormField
                                control={form.control}
                                name="bindPassword"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel htmlFor="bind-password">Bind Password</FormLabel>
                                        <FormControl>
                                            <PasswordInput
                                                id="bind-password"
                                                value={field.value}
                                                onChange={field.onChange}
                                                placeholder="Enter service account password"
                                                disabled={field.disabled}
                                                aria-describedby="bind-password-help"
                                                aria-invalid={!!form.formState.errors.bindPassword}
                                            />
                                        </FormControl>
                                        <FormDescription id="bind-password-help">
                                            The password for the service account. This will be encrypted at rest.
                                        </FormDescription>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />
                        </div>

                        <Separator className="my-4" />

                        {/* User Search Section */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide flex items-center gap-2">
                                <Users className="h-4 w-4" aria-hidden="true" />
                                User Search Configuration
                            </h3>

                            {/* User Search Base */}
                            <FormField
                                control={form.control}
                                name="userSearchBase"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel htmlFor="search-base">User Search Base</FormLabel>
                                        <FormControl>
                                            <Input
                                                id="search-base"
                                                placeholder="OU=Users,DC=company,DC=com"
                                                {...field}
                                                aria-describedby="search-base-help"
                                            />
                                        </FormControl>
                                        <FormDescription id="search-base-help">
                                            The base DN where user searches will start.
                                        </FormDescription>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />

                            {/* User Search Filter */}
                            <FormField
                                control={form.control}
                                name="userSearchFilter"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel htmlFor="search-filter">User Search Filter</FormLabel>
                                        <FormControl>
                                            <Input
                                                id="search-filter"
                                                placeholder="(sAMAccountName={username})"
                                                {...field}
                                                aria-describedby="search-filter-help"
                                            />
                                        </FormControl>
                                        <FormDescription id="search-filter-help">
                                            LDAP filter to find users. Use {